---
javax:
  persistence:
    schema-generation:
      scripts:
        action: create
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/uuid_test
    username: postgres
    password: 198725
  jpa:
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update